---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_ROOT}/heimdall/data:/config
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SSL}:443
    restart: unless-stopped
